<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UslugaOstvarena extends \App\Models\Entities\UslugaOstvarena implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'iduslostv', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'komentar', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'ocena', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'obrisano', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'idrez', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'idusl'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'iduslostv', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'komentar', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'ocena', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'obrisano', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'idrez', '' . "\0" . 'App\\Models\\Entities\\UslugaOstvarena' . "\0" . 'idusl'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UslugaOstvarena $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIduslostv(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIduslostv();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIduslostv', []);

        return parent::getIduslostv();
    }

    /**
     * {@inheritDoc}
     */
    public function getKomentar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKomentar', []);

        return parent::getKomentar();
    }

    /**
     * {@inheritDoc}
     */
    public function getOcena(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOcena', []);

        return parent::getOcena();
    }

    /**
     * {@inheritDoc}
     */
    public function getObrisano(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObrisano', []);

        return parent::getObrisano();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrez(): \App\Models\Entities\Rezervacija
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrez', []);

        return parent::getIdrez();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusl(): \App\Models\Entities\Usluga
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusl', []);

        return parent::getIdusl();
    }

    /**
     * {@inheritDoc}
     */
    public function setIduslostv(int $iduslostv): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIduslostv', [$iduslostv]);

        parent::setIduslostv($iduslostv);
    }

    /**
     * {@inheritDoc}
     */
    public function setKomentar(?string $komentar): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKomentar', [$komentar]);

        parent::setKomentar($komentar);
    }

    /**
     * {@inheritDoc}
     */
    public function setOcena(?string $ocena): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOcena', [$ocena]);

        parent::setOcena($ocena);
    }

    /**
     * {@inheritDoc}
     */
    public function setObrisano(string $obrisano): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObrisano', [$obrisano]);

        parent::setObrisano($obrisano);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrez(\App\Models\Entities\Rezervacija $idrez): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrez', [$idrez]);

        parent::setIdrez($idrez);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusl(\App\Models\Entities\Usluga $idusl): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusl', [$idusl]);

        parent::setIdusl($idusl);
    }

}
