<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usluga extends \App\Models\Entities\Usluga implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
  'idmaj' => NULL,
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
  'idmaj' => NULL,
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        unset($this->idmaj);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);

    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'idusl', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'cena', 'idmaj', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'tagovi'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'idusl', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'cena', '' . "\0" . 'App\\Models\\Entities\\Usluga' . "\0" . 'tagovi'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usluga $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->idmaj);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdusl(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdusl();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusl', []);

        return parent::getIdusl();
    }

    /**
     * {@inheritDoc}
     */
    public function getNaziv(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaziv', []);

        return parent::getNaziv();
    }

    /**
     * {@inheritDoc}
     */
    public function getOpis(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpis', []);

        return parent::getOpis();
    }

    /**
     * {@inheritDoc}
     */
    public function getCena(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCena', []);

        return parent::getCena();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmaj(): \App\Models\Entities\Korisnik
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmaj', []);

        return parent::getIdmaj();
    }

    /**
     * {@inheritDoc}
     */
    public function getTagovi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTagovi', []);

        return parent::getTagovi();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusl(int $idusl): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusl', [$idusl]);

        parent::setIdusl($idusl);
    }

    /**
     * {@inheritDoc}
     */
    public function setNaziv(string $naziv): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaziv', [$naziv]);

        parent::setNaziv($naziv);
    }

    /**
     * {@inheritDoc}
     */
    public function setOpis(string $opis): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpis', [$opis]);

        parent::setOpis($opis);
    }

    /**
     * {@inheritDoc}
     */
    public function setCena(float $cena): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCena', [$cena]);

        parent::setCena($cena);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmaj(\App\Models\Entities\Korisnik $idmaj): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmaj', [$idmaj]);

        parent::setIdmaj($idmaj);
    }

    /**
     * {@inheritDoc}
     */
    public function setTagovi($tagovi): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTagovi', [$tagovi]);

        parent::setTagovi($tagovi);
    }

}
